before_script:
  - apt-get update
  # needed to download NuGet
  - apt-get install -y curl

stages:
  - build
  - test

newmono_build:
  image: ubuntu:18.04
  stage: build
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh
    - ./configure
    - make
    - make install
