before_script:
  - apt-get update
  - apt-get install -y automake autoconf

stages:
  - build
  - test

newmono_build:
  image: ubuntu:18.04
  stage: build
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh
    - ./configure --profile=gnome
    - make
    - make install
